#pragma once

//
#include <SDL3/SDL.h>
//#include "spdlog/spdlog.h"

namespace engine {

//namespace log = spdlog;

using Event = SDL_Event;

enum class WindowEventType 
{
    SHOWN = SDL_EVENT_WINDOW_SHOWN,
    HIDDEN = SDL_EVENT_WINDOW_HIDDEN,
    EXPOSED = SDL_EVENT_WINDOW_EXPOSED,
    MOVED = SDL_EVENT_WINDOW_MOVED,
    RESIZED = SDL_EVENT_WINDOW_RESIZED,
    PIXEL_SIZE_CHANGED = SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED,
    METAL_VIEW_RESIZED = SDL_EVENT_WINDOW_METAL_VIEW_RESIZED,
    MINIMIZED = SDL_EVENT_WINDOW_MINIMIZED,
    MAXIMIZED = SDL_EVENT_WINDOW_MAXIMIZED,
    RESTORED = SDL_EVENT_WINDOW_RESTORED,
    MOUSE_ENTER = SDL_EVENT_WINDOW_MOUSE_ENTER,
    MOUSE_LEAVE = SDL_EVENT_WINDOW_MOUSE_LEAVE,
    FOCUS_GAINED = SDL_EVENT_WINDOW_FOCUS_GAINED,
    FOCUS_LOST = SDL_EVENT_WINDOW_FOCUS_LOST,
    CLOSE_REQUESTED = SDL_EVENT_WINDOW_CLOSE_REQUESTED,
    HIT_TEST = SDL_EVENT_WINDOW_HIT_TEST,
    ICCPROF_CHANGED = SDL_EVENT_WINDOW_ICCPROF_CHANGED,
    DISPLAY_CHANGED = SDL_EVENT_WINDOW_DISPLAY_CHANGED,
    DISPLAY_SCALE_CHANGED = SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED,
    SAFE_AREA_CHANGED = SDL_EVENT_WINDOW_SAFE_AREA_CHANGED,
    OCCLUDED = SDL_EVENT_WINDOW_OCCLUDED,
    ENTER_FULLSCREEN = SDL_EVENT_WINDOW_ENTER_FULLSCREEN,
    LEAVE_FULLSCREEN = SDL_EVENT_WINDOW_LEAVE_FULLSCREEN,
    DESTROYED = SDL_EVENT_WINDOW_DESTROYED,
    HDR_STATE_CHANGED = SDL_EVENT_WINDOW_HDR_STATE_CHANGED
};

    
enum class WindowFlags : Uint64 
{
    FULLSCREEN = SDL_WINDOW_FULLSCREEN,
    OPENGL = SDL_WINDOW_OPENGL,
    OCCLUDED = SDL_WINDOW_OCCLUDED,
    HIDDEN = SDL_WINDOW_HIDDEN,
    BORDERLESS = SDL_WINDOW_BORDERLESS,
    RESIZABLE = SDL_WINDOW_RESIZABLE,
    MINIMIZED = SDL_WINDOW_MINIMIZED,
    MAXIMIZED = SDL_WINDOW_MAXIMIZED,
    MOUSE_GRABBED = SDL_WINDOW_MOUSE_GRABBED,
    INPUT_FOCUS = SDL_WINDOW_INPUT_FOCUS,
    MOUSE_FOCUS = SDL_WINDOW_MOUSE_FOCUS,
    EXTERNAL = SDL_WINDOW_EXTERNAL,
    MODAL = SDL_WINDOW_MODAL,
    HIGH_PIXEL_DENSITY = SDL_WINDOW_HIGH_PIXEL_DENSITY,
    MOUSE_CAPTURE = SDL_WINDOW_MOUSE_CAPTURE,
    MOUSE_RELATIVE_MODE = SDL_WINDOW_MOUSE_RELATIVE_MODE,
    ALWAYS_ON_TOP = SDL_WINDOW_ALWAYS_ON_TOP,
    UTILITY = SDL_WINDOW_UTILITY,
    TOOLTIP = SDL_WINDOW_TOOLTIP,
    POPUP_MENU = SDL_WINDOW_POPUP_MENU,
    KEYBOARD_GRABBED = SDL_WINDOW_KEYBOARD_GRABBED,
    VULKAN = SDL_WINDOW_VULKAN,
    METAL = SDL_WINDOW_METAL,
    TRANSPARENT = SDL_WINDOW_TRANSPARENT,
    NOT_FOCUSABLE = SDL_WINDOW_NOT_FOCUSABLE
};


}